install.packages('MASS', repos='http://cran.us.r-project.org')
install.packages('devtools', repos='http://cran.us.r-project.org')
install.packages('Rcpp', repos='http://cran.us.r-project.org')
install.packages('zoo', repos='http://cran.us.r-project.org')
install.packages('DBI', repos='http://cran.us.r-project.org')
install.packages('assertthat', repos='http://cran.us.r-project.org')
install.packages('tibble', repos='http://cran.us.r-project.org')
source("https://raw.githubusercontent.com/r-pkgs/remotes/master/install-github.R")$value("r-pkgs/remotes")
devtools::install_github("hrbrmstr/streamgraph")

install.packages('rattle', repos='http://cran.us.r-project.org')
install.packages('ggplot2', repos='http://cran.us.r-project.org')
install.packages('plotly', repos='http://cran.us.r-project.org')
install.packages('rmarkdown', repos='http://cran.us.r-project.org')
